### PR TITLE
Bump Eclipse version in test to 2022.2

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves failure when trying to run the test (at least on s034):

`OSError: The executable: '/prog/ecl/grid/2017.1/bin/linux_x86_64/eclipse.exe' can not be executed by user
`

**Approach**
Bump.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by sondreso** [comment]
Jenkins add to whitelist

**Comment by hnformentin** [comment]
Can you please create an issue to unpin mypy later on and link it here?

**Review by hnformentin — APPROVED** [review]
LGTM!

**Pull request merged**
